# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ofimatica Easy
email: ofimaticaeasy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  En OfimaticaEasy encontraras tutoriales relacionados con programaci칩n, servidores, noticias, etc.
  Podr치s aprendes leguajes de programaci칩n tales como php 7, java, javascript ...
  Si te gusta podr치s subcribirte a nuestra newsletter.
keywords: programacion, tecnologia, php tutorial, java tutorial, javascript tutorial, noticias, tutoriales programacion, php 7, ofimaticaeasy, ofimatica, jre
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ofimaticaeasy.es" # the base hostname & protocol for your site
twitter_username: ofimaticaeasy
github_username:  ofimaticaeasy
permalink: pretty
encoding: utf-8

# Build settings
markdown: kramdown


# gems plugin
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# cache
assets:
  cache: .my_cache_folder

# Google services
google_analytics: UA-54015456-2
